# Generated by Django 5.1.7 on 2025-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='days',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
